name: test-gpt5
services:
  server:
    build: ./server
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://localhost:3000
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - server
